### ISSUE TITLE
MenuItem 设置 customClass 无效

### ISSUE THREAD

**Issue by ychost** [GitHub-Laziji/menujs#11]
```
          { label: '删除节点', icon: 'el-icon-delete', customClass: 'deleteMenuItem' }
```
类似这种设置，并没有将 deleteMenuItem 插入到菜单的 dom 里面，全局的 customClass 是有效的

**Comment by GitHub-Laziji** [comment]
customClass 指该菜单项 展开的整体菜单的class, 若要对某一个item自定义样式 可以用
```css
.custom_class .menu_item {
    ...
}
```

**Comment by starxg** [comment]
> customClass 指该菜单项 展开的整体菜单的class, 若要对某一个item自定义样式 可以用
> 
> ```css
> .custom_class .menu_item {
>     ...
> }
> ```

这个是对所有的menu_item加样式了吧？如果想单独对某个item加class怎么做呢？

**Comment by starxg** [comment]
在 contextmenu.umd.js 文件中添加这个解决了
![avatar](https://p.pstatp.com/origin/1386b000313156dd25640)

**Comment by starxg** [comment]
在 contextmenu.umd.js 文件中添加这个解决了
`staticClass: "menu_item_label " + item.customClass`

主要加上这个属性 item.customClass
