### ISSUE TITLE
onClick 方法不执行

### ISSUE THREAD

**Issue by serverlet** [GitHub-Laziji/menujs#17]
vue版本2.5.17
element-ui版本 2.4.6
本插件版本 1.3.13
debugger发现点击优先执行 item的close 方法
`onPrintmenu(event) {
        this.$contextmenu({
          items: [{
            label: "打印(P)...",
            icon: "el-icon-printer",
            disabled: false,
            hidden: false,
            onClick: () => {
              console.info('fileUrl:', event);
            }
          }],
          event,
          minWidth: 100
        });
      }`

**Comment by unull** [comment]
> vue版本2.5.17
> element-ui版本 2.4.6
> 本插件版本 1.3.13
> debugger发现点击优先执行 item的close 方法
> `onPrintmenu(event) { this.$contextmenu({ items: [{ label: "打印(P)...", icon: "el-icon-printer", disabled: false, hidden: false, onClick: () => { console.info('fileUrl:', event); } }], event, minWidth: 100 }); }`

同遇到这个问题，请问能够解决吗？

**Comment by ldwqh0** [comment]
我也是，不知道什么原因

**Comment by fh345392977** [comment]
你的编译环境导致`this.$style`里面是空的，源码里是根据`const menus = getElementsByClassName(this.$style.menu)`来找元素的，所以先执行了$destory(),visible 变为了false，onClick也就不执行了。

方法一检查编译环境，方法二，改源码写死

**Comment by xuyang60** [comment]
请问编译环境如果检查，从哪几个方面入手？ @fh345392977

**Comment by fh345392977** [comment]
> 请问编译环境如果检查，从哪几个方面入手？ @fh345392977

我直接改的源码

**Comment by lyhwoc** [comment]
this.$style 对应下面的值：

```html
<style module>
.menu,
.menu_item,
.menu_item__clickable,
.menu_item__unclickable {
  box-sizing: border-box;
}
</style>
```

需要配置 [css modules](https://vue-loader.vuejs.org/zh/guide/css-modules.html#%E7%94%A8%E6%B3%95)

@xuyang60

**Comment by lyhwoc** [comment]
最简单的解决方案：

使用 `import Contextmenu from "vue-contextmenujs/dist/contextmenu.umd"` 代替 `import Contextmenu from "vue-contextmenujs`

**Comment by GitHub-Laziji** [comment]
`1.4.9`后不再使用`<style module>`
