### ISSUE TITLE
el-tree 中当浏览器高度不足时，显示位置不对，无法显示菜单的第一行

### ISSUE THREAD

**Issue by 1607941875** [GitHub-Laziji/menujs#26]
![image](https://user-images.githubusercontent.com/59784883/174432855-d358bd5e-e8ef-48c7-a0ec-b1f1c76332a1.png)

**Comment by AnnaAllen** [comment]
我也遇到了这个问题，请问要怎么解决

**Comment by GitHub-Laziji** [comment]
感谢反馈，已修复
`vue-contextmenujs@1.4.0`

测试地址 [https://codepen.io/laziji/pen/vYEZebK](https://codepen.io/laziji/pen/vYEZebK)

**Comment by GitHub-Laziji** [comment]
感谢反馈，已修复
`vue-contextmenujs@1.4.0`

测试地址 [https://codepen.io/laziji/pen/vYEZebK](https://codepen.io/laziji/pen/vYEZebK)
