### ISSUE TITLE
升级 vue2.7 菜单不能正常隐藏，会一直展示

### ISSUE THREAD

**Issue by doudou-dream** [GitHub-Laziji/menujs#27]
"vue": "^2.7.0",
    "vue-demi": "^0.13.1",
    "vue-loader": "^15.10.0"
    依赖和之前相比有这些配置更改

**Comment by doudou-dream** [comment]
![image](https://user-images.githubusercontent.com/24222969/177071008-96fe4771-5b68-4274-b779-e2fb730f73b3.png)

经过测试，升级vue2.7导致的
当visible变为false;v-if没有把dom元素销毁，我尝试使用 this.$refs.menu.remove()可以正常销毁

**Comment by junglehunter96** [comment]
我今天也遇到了

**Comment by lqzhgood** [comment]
感觉作者也不太想更新的样子。
我 fork 后重构了一版，修了一些 Bug 
https://github.com/lqzhgood/vue-context-menu

`npm i @lqzh/vue-context-menu`

**Comment by GitHub-Laziji** [comment]
感谢反馈，已修复
vue-contextmenujs@1.4.0

**Comment by doudou-dream** [comment]
> 感谢反馈，已修复
> 
> 测试地址https://codepen.io/laziji/pen/vYEZebK

嗯嗯，测试正常
