### ISSUE TITLE
1.4.7版本MenuOptions的x和y属性与之前版本不兼容

### ISSUE THREAD

**Issue by l-mh-95** [GitHub-Laziji/menujs#28]
之前的代码实现
![image](https://user-images.githubusercontent.com/87355750/188254045-fb395bf0-7c19-43a5-a82a-184621fc7485.png)

1.4.7版本的实现
![image](https://user-images.githubusercontent.com/87355750/188254069-5ef9832b-511c-4588-89c3-86aa025cf973.png)

**Comment by Smileytear** [comment]
遇到了同样的问题，position是未定义，不知道是不是代码写错了，this.position.x感觉应该是options.x

**Comment by GitHub-Laziji** [comment]
感谢反馈，最新版1.4.9已修复
