### ISSUE TITLE
监听键盘快捷键事件之后如何销毁右键菜单

### ISSUE THREAD

**Issue by selfdialog** [GitHub-Laziji/menujs#8]
document.onkeyup = (e) => { // 右键菜单快捷键
                let key = e.key.toLowerCase();
                switch (key) {
                    case "a":
                      // 这里右键菜单出来了
                      // this.$contextmenu({})已经实例化出来了
                      // 监听到键盘的a键之后，怎么销毁右键菜单，点击右键菜单事件肯定没问题
                        break;
                    default:
                        break;
                }
}

**Comment by GitHub-Laziji** [comment]
可以调用`this.$contextmenu.destroy()`手动关闭
